[package]
name = "mextk-libc"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"
description = "A subset of libc needed for building mods for Super Smash Brothers Melee"
repository = "https://github.com/jam1garner/mextk-rs"
license = "MIT"
