[package]
name = "mextk-hello-world"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mextk-sys = { path = "../mextk-sys" }
